language: php

php:
  - 7.0
  - 7.2
  - 7.4
  - 8.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'

<<<<<<< HEAD
# phpunit testing is disabled as dist vendor is cleared by removing unneeded files
#script:
#  - vendor/bin/phpunit
=======
script:
  - vendor/bin/phpunit
>>>>>>> fcb18e56f0ef2ee4622ec16073a1ed2c9f329ec4
